version: '3.9'

services:
  db:
    image: postgres:15
    container_name: dtifitz-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dtifitzdb 
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
